### ISSUE TITLE
double pegleg installation operations

### ISSUE THREAD

**Issue by 321nick** [kaptain-kavern/ADogSaid#26] opened 2016-08-04 06:23 UTC
as the title says: http://i.imgur.com/wVHytbP.png

i have dieters A dog said-EPOE , which , as dieter says, supposed too come after A dog Said and EPOE, 

i got the newest version of a dog said, unsubscribed from the old version, and re-subscribed too the new one, etc. 

any help? i can post log files if it will help, or if i can find them.

**Comment by kaptain-kavern** [comment] 2016-08-04 06:41
Hey thanks for reporting. I just saw a similar comment in Reddit, was it you too @321nick ?

I'm not in front of my gaming rig ATM but will investigate.

@spoonshortage @nattiejim  
The only place where we have [added the word pegleg](https://github.com/kaptain-kavern/ADogSaid/search?utf8=%E2%9C%93&q=pegleg) is in our recipe files, so if one of the two other mods add it via the race files, it will add a 2nd option in the health menu. I'm quasi certain that EPOE itself doesn't mess with the animal race files. So it must be the "EPOE benches add on". I can't verify it ATM I'm in front of computer

**Comment by 321nick** [comment] 2016-08-04 06:43
ok, but besides having 2 options, is it any- game breaking bugs? like, if i continue to play with it regardless, will it be ok? should i just use any option for attaching peglegs?

**Comment by kaptain-kavern** [comment] 2016-08-04 06:50
The problem is they have exactly the same name. I guess they are sorted by order in the mod list and the first one being the good one (from "raw ADogSaid" I mean).

You can continue to play but if it came from ADogSaid-EPOE and it is corrected I'm not sure if some already installed pegleg will not disappear. To me nothing too bad

**Comment by 321nick** [comment] 2016-08-04 06:51
ok, thanks @kaptain-kavern

**Comment by kaptain-kavern** [comment] 2016-08-04 17:25
Ok, i checked some hints;
1. Doesn't came from **ADogSaid-EPOE** : There is only crafting recipes in it. No surgeries.
2. Doesn't came from **EPOE** either : On the screenshot it's wrote : _Animal Peg Leg_. It must came from ADS
3. But .... In all of our code, [we only use the word **pegleg** one time](https://github.com/kaptain-kavern/ADogSaid/search?utf8=%E2%9C%93&q=%22pegleg%22&type=Code)

So the more i think/search the more i came to the conclusion it came from your setup @321nick. It looks like there is still some old (unused now since last patch) files in your ADS folder. Namely some ThingsDefRaces folder/files. But they're not supposed to still be here because we have changed the way the mod works.

Can you go to your mod folder and completely erase ADogSaid folder - with **Steam** closed (i'm guessing ... because i don't use Steam at all because of this kind of problems in fact). After lauching Steam again i guess it will re-download the mod (because of the subscription "thing") again and i hope this will fix it.

---

|  |  |
| --- | --- |
| ![Steam](http://img03.deviantart.net/e4d4/i/2006/005/e/d/steam_sucks_by_denolf.jpg) | In fact, it was always recommended to completely erase old folders in order to update mods. Steam Workshop seems to not being able to understand this + it will break people savegames by autoupdating mods without prompting user. |

**Comment by inkyspoon** [comment] 2016-08-04 17:42
yep. you are right @kaptain-kavern. I just checked my own workshop folder for A Dog Said..
its in C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\730360526\
and lo' and behold steam didn't erase the old races folder when updating... so everyone who had the old workshop item subscribed needs to delete their old folder completely and subscribe to the new one. Though I am curious how that happened because nattiejim uploaded it as new item and the folder ID should have been different than the old one... ahh well 10/10 would steam again..:triumph:

**Comment by nattiejim** [comment] 2016-08-06 02:31
Closing as this seems to be resolved with a fix.

**Closed as completed** 2016-08-06 02:31 UTC
Labels: bug
